# Server Port Configuration
server.port=8081

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5433/muleguard_db
spring.datasource.username=postgres
spring.datasource.password=root 

# Hibernate / JPA Settings
# 'update' automatically creates your SQL tables for you!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

